- name: Install nodejs and npm if not installed
  hosts: production
  tasks:
    - name: Update apt repo and cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Check if Node.js and npm are installed
      command: dpkg -l nodejs npm
      register: node_check
      changed_when: false

    - name: Install Node.js and npm if not installed
      apt:
        name:
          - nodejs
          - npm
        state: latest
        update_cache: yes
      when: "'nodejs' not in node_check.stdout or 'npm' not in node_check.stdout"

- name: Deploy nodejs app
  hosts: production
  tasks:
    - name: Ensure the destination directory exists
      file:
        path: /home/kareem/myapp
        state: directory
        mode: 0755
        owner: kareem
        group: kareem

    - name: Copy nodejs folder to the server
      copy:
        src: /home/kareem/Ansible-learn/Aws-Docker/myapp.tgz
        dest: /home/kareem/myapp/myapp.tgz

    - name: Unpack the nodejs file
      unarchive:
        src: /home/kareem/myapp/myapp.tgz
        dest: /home/kareem/myapp
        remote_src: yes

    - name: Install dependencies
      npm:
        path: /home/kareem/myapp

    - name: Start the application
      command: node /home/kareem/myapp/src/index.js
      async: 1000
      poll: 0

