---
- hosts: production
  tasks:
  - name: Install apache2 and libapache2-mod-php packages
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: present

  - name: Uninstall pip3
    apt:
      name: pip3
      state: absent
