---
- hosts: workstation
  tasks:
    - name: ensure destination directory exists
      file:
        path: /var/www/html
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: copy from src to dest
      copy:
        src: file/default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'

    - name: install unzip
      package:
        name: unzip
        state: present

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: '0755'
        owner: root
        group: root

