- hosts: file_servers
  tasks:
    - name: Install Weather app
      tags: files, Ubuntu1
      snap:
        name: gnome-weather
        state: present

- hosts: web_servers
  tasks:
    - name: Install Postgres && Mariadb service
      tags: service, Ubuntu2
      package:
        name: 
          - postgresql
          - mariadb-server  
        state: present
        update_cache: yes

    - name: Activating Postgres service
      tags: active, postgresql
      service:
        name: postgresql
        state: started  
        enabled: yes

    - name: Activating Mariadb service
      tags: active, mariadb
      service:
        name: mariadb
        state: started
        enabled: yes     
